src/Entity/Project.php
<?php

namespace App\Entity;

use App\Repository\ProjectRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProjectRepository::class)
 */
class Project
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $label;

    /**
     * @ORM\Column(type="date")
     */
    private $creation_date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     */
    private $Manager;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTimeInterface $creation_date): self
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getManager(): ?User
    {
        return $this->Manager;
    }

    public function setManager(?User $Manager): self
    {
        $this->Manager = $Manager;

        return $this;
    }


    public function __toString(): ?User
    {
        return $this->Manager;
    }
}

src/Entity/Schedule.php
<?php

namespace App\Entity;

use App\Repository\ScheduleRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ScheduleRepository::class)
 */
class Schedule
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $timestamp;

    /**
     * @ORM\ManyToOne(targetEntity=Task::class)
     */
    private $Task;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTimestamp(): ?string
    {
        return $this->timestamp;
    }

    public function setTimestamp(string $timestamp): self
    {
        $this->timestamp = $timestamp;

        return $this;
    }

    public function getTask(): ?Task
    {
        return $this->Task;
    }

    public function setTask(?Task $Task): self
    {
        $this->Task = $Task;

        return $this;
    }
}

src/Entity/Task.php
<?php

namespace App\Entity;

use App\Repository\TaskRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TaskRepository::class)
 */
class Task
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $label;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $state;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     */
    private $Employee;

    /**
     * @ORM\ManyToOne(targetEntity=Project::class)
     */
    private $Project;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(string $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getEmployee(): ?User
    {
        return $this->Employee;
    }

    public function setEmployee(?User $Employee): self
    {
        $this->Employee = $Employee;

        return $this;
    }

    public function getProject(): ?Project
    {
        return $this->Project;
    }

    public function setProject(?Project $Project): self
    {
        $this->Project = $Project;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $job_title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $phone_number;

    /**
     * @ORM\Column(type="date")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    public $Username;

    /**
     * @ORM\ManyToOne(targetEntity=Role::class)
     */
    private $Role;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->Username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getJobTitle(): ?string
    {
        return $this->job_title;
    }

    public function setJobTitle(string $job_title): self
    {
        $this->job_title = $job_title;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }



    public function setUsername(string $Username): self
    {
        $this->Username = $Username;

        return $this;
    }

    public function getIsVerified(): ?bool
    {
        return $this->isVerified;
    }

    public function getRole(): ?Role
    {
        return $this->Role;
    }

    public function setRole(?Role $Role): self
    {
        $this->Role = $Role;

        return $this;
    }
}

src/Form/ScheduleType.php
<?php

namespace App\Form;

use App\Entity\Schedule;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ScheduleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('timestamp')
            ->add('Task')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Schedule::class,
        ]);
    }
}

src/Controller/ScheduleController.php
<?php

namespace App\Controller;

use App\Entity\Schedule;
use App\Entity\Task;
use App\Form\ScheduleType;
use App\Repository\ScheduleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
//use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\VarDumper\Cloner\Data;

/**
 * @Route("/schedule")
 */
class ScheduleController extends AbstractController
{
    /**
     * @Route("/", name="app_schedule_index", methods={"GET"})
     */
    public function index(ScheduleRepository $scheduleRepository): Response
    {
        return $this->render('schedule/index.html.twig', [
            'schedules' => $scheduleRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_schedule_new", methods={"GET", "POST"})
     */
    public function new(Request $request, ScheduleRepository $scheduleRepository , ManagerRegistry $doctrine): Response

    { 
        $task = new Task();
        $schedule = new Schedule();
        $Data = json_decode($request->query->get('Data'),true);

        $repository = $doctrine->getRepository(Task::class);
        $task = $repository->find($Data["Task"]);

      
       
        $schedule->setTimestamp($Data["Time"]);
        $schedule->setTask( $task);
        $scheduleRepository->add($schedule);
    

        return $this->renderForm('schedule/show.html.twig', [
            'schedule' => $schedule,
            
        ]);
    }

    /**
     * @Route("/{id}", name="app_schedule_show", methods={"GET"})
     */
    public function show(Schedule $schedule): Response
    {
        return $this->render('schedule/show.html.twig', [
            'schedule' => $schedule,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_schedule_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Schedule $schedule, ScheduleRepository $scheduleRepository): Response
    {
        $form = $this->createForm(ScheduleType::class, $schedule);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $scheduleRepository->add($schedule);
            return $this->redirectToRoute('app_schedule_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('schedule/edit.html.twig', [
            'schedule' => $schedule,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_schedule_delete", methods={"POST"})
     */
    public function delete(Request $request, Schedule $schedule, ScheduleRepository $scheduleRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$schedule->getId(), $request->request->get('_token'))) {
            $scheduleRepository->remove($schedule);
        }

        return $this->redirectToRoute('app_schedule_index', [], Response::HTTP_SEE_OTHER);
    }

/**
* @Route("/saveTime" ,name="saveTime")
*/
public function saveTime(Request $request)
{
    $Data = json_decode($request->query->get('Data'),true);
    dump($Data);die;
  

  /*

    return new JsonResponse(array(
        'status' => true,
        'message' => "Saved :"),
        200
    );
*/
  

}
}

templates/schedule/_delete_form.html.twig
<form method="post" action="{{ path('app_schedule_delete', {'id': schedule.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ schedule.id) }}">
    <button class="btn">Delete</button>
</form>

templates/schedule/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/schedule/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Schedule{% endblock %}

{% block body %}
    <h1>Edit Schedule</h1>

    {{ include('schedule/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_schedule_index') }}">back to list</a>

    {{ include('schedule/_delete_form.html.twig') }}
{% endblock %}

templates/schedule/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Project index{% endblock %}

{% block body %}
   <div class="pcoded-content">
                        <div class="pcoded-inner-content">

                            <div class="main-body">
                                <div class="page-wrapper">

                                    


                                    <div class="page-body">

                                        
                                        <div class="card">
                                            <div class="card-header">
                                                <h5>Task tracking List</h5>
                                                
                                            </div>
                                            <div class="card-block">
                                                <div class="dt-responsive table-responsive">
                                                    <table id="table-style-hover"
                                                        class="table table-striped table-hover table-bordered nowrap">
                                                        <thead>
                                                            <tr>
                                                            <th>Id</th>
                                                            <th>Label</th>
                                                            <th>Manager</th>
                                                            <th>Affected to</th>
                                                            <th>Projcet</th>
                                                            <th>Timer</th>
                                                            
                                                            
                                                           </tr>
                                                        </thead>
                                                        <tbody>
                                                            {% for schedule in schedules %}
                                                                <tr>
                                                                   <td>{{ schedule.id }}</td>
                
                                                                     <td>{{ schedule.task.getLabel }}</td>
                                                                     <td>{{ schedule.task.project.manager.username}}</td>
                                                                     <td>{{ schedule.task.Employee.getUsername}}</td>
                                                                     <td>{{ schedule.task.project.getLabel }}</td>
                                                                     <td>{{ schedule.timestamp }}</td>
                
                
                                                                    </td>
                                                                </tr>
                                                            {% else %}
                                                                <tr>
                                                                    <td colspan="12">no records found</td>
                                                                </tr>
                                                            {% endfor %}
                                                            </tbody>
                                                        <tfoot>
                                                            <tr>
                                                              <th>Id</th>
                                                            <th>Label</th>
                                                            <th>Manager</th>
                                                            <th>Affected to</th>
                                                            <th>Projcet</th>
                                                            <th>Timer</th>
                                                            </tr>
                                                        </tfoot>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>

                                
                            </div>
                            <div id="styleSelector">
                            </div>
                        </div>
                    </div>
    
{% endblock %}

templates/schedule/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Schedule{% endblock %}

{% block body %}
    <h1>Create new Schedule</h1>

    {{ include('schedule/_form.html.twig') }}

    <a href="{{ path('app_schedule_index') }}">back to list</a>
{% endblock %}

templates/schedule/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Schedule{% endblock %}

{% block body %}
    <h1>Schedule</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ schedule.id }}</td>
            </tr>
            <tr>
                <th>Timestamp</th>
                <td>{{ schedule.timestamp }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_schedule_index') }}">back to list</a>

    <a href="{{ path('app_schedule_edit', {'id': schedule.id}) }}">edit</a>

    {{ include('schedule/_delete_form.html.twig') }}
{% endblock %}