src/Entity/Project.php
<?php

namespace App\Entity;

use App\Repository\ProjectRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProjectRepository::class)
 */
class Project
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $label;

    /**
     * @ORM\Column(type="date")
     */
    private $creation_date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     */
    private $Manager;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTimeInterface $creation_date): self
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getManager(): ?User
    {
        return $this->Manager;
    }

    public function setManager(?User $Manager): self
    {
        $this->Manager = $Manager;

        return $this;
    }


    public function __toString(): ?User
    {
        return $this->Manager;
    }
}

src/Form/ProjectType.php
<?php

namespace App\Form;

use App\Entity\Project;
use App\Entity\User;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class ProjectType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('label')
            
            // ->add('Manager')
            ->add('status')
            ->add('Manager', EntityType::class, [
                // looks for choices from this entity
                'class' => User::class,
            
                // uses the User.username property as the visible option string
                'choice_label' => 'username',
            
                // used to render a select box, check boxes or radios
                // 'multiple' => true,
                // 'expanded' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Project::class,
        ]);
    }
}

src/Controller/ProjectController.php
<?php

namespace App\Controller;

use App\Entity\Project;
use App\Form\ProjectType;
use App\Repository\ProjectRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use DateTime;


/**
 * @Route("/project")
 */
class ProjectController extends AbstractController
{
    /**
     * @Route("/", name="app_project_index", methods={"GET"})
     */
    public function index(ProjectRepository $projectRepository): Response
    {
        return $this->render('project/index.html.twig', [
            'projects' => $projectRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_project_new", methods={"GET", "POST"})
     */
    public function new(Request $request, ProjectRepository $projectRepository): Response
    {
        $project = new Project();
        $form = $this->createForm(ProjectType::class, $project);
        $form->handleRequest($request);
        $now = new DateTime();
        $now->format('Y-m-d H:i:s');    // MySQL datetime format
        $project->setCreationDate($now);

        if ($form->isSubmitted() && $form->isValid()) {
            $projectRepository->add($project);
            return $this->redirectToRoute('app_project_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('project/new.html.twig', [
            'project' => $project,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_project_show", methods={"GET"})
     */
    public function show(Project $project): Response
    {
        return $this->render('project/show.html.twig', [
            'project' => $project,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_project_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Project $project, ProjectRepository $projectRepository): Response
    {
        $form = $this->createForm(ProjectType::class, $project);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $projectRepository->add($project);
            return $this->redirectToRoute('app_project_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('project/edit.html.twig', [
            'project' => $project,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_project_delete", methods={"POST"})
     */
    public function delete(Request $request, Project $project, ProjectRepository $projectRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$project->getId(), $request->request->get('_token'))) {
            $projectRepository->remove($project);
        }

        return $this->redirectToRoute('app_project_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/project/_delete_form.html.twig
<form method="post" action="{{ path('app_project_delete', {'id': project.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ project.id) }}">
    <button class="btn">Delete</button>
</form>

templates/project/_form.html.twig
{{ form_start(form) }}
    
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/project/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Project{% endblock %}

{% block body %}
    <h1>Edit Project</h1>

    {{ include('project/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_project_index') }}">back to list</a>

    {{ include('project/_delete_form.html.twig') }}
{% endblock %}

templates/project/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Project index{% endblock %}

{% block body %}
   <div class="pcoded-content">
                        <div class="pcoded-inner-content">

                            <div class="main-body">
                                <div class="page-wrapper">

                                    


                                    <div class="page-body">

                                        
                                        <div class="card">
                                            <div class="card-header">
                                                <h3>Project List</h3>
                                              
                                            </div>
                                            <div class="card-block">
                                                <div class="dt-responsive table-responsive">
                                                    <table id="table-style-hover"
                                                        class="table table-striped table-hover table-bordered nowrap">
                                                        <thead>
                                                            <tr>
                                                                <th>Id</th>
                                                                <th>Label</th>
                                                                <th>Creation_date</th>
                                                                <th>Manager</th>
                                                                <th>Status</th>
                                                                <th>actions</th>
                                                               
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            {% for project in projects %}
                                                                <tr>
                                                                   <td>{{ project.id }}</td>
                                                                   <td>{{ project.label }}</td>
                                                                   <td>{{ project.creationDate ? project.creationDate|date('Y-m-d') : '' }}</td>
                                                                   <td>{{ project.Manager.getUsername }}</td>
                                                                   <td>{{ project.status }}</td>
                
                                                                    <td>
                                                                        <button class="btn btn-info btn-round" > <a href="{{ path('app_project_show', {'id': project.id}) }}">show</a></button >

                                                                        <button class="btn btn-success btn-round" > <a href="{{ path('app_project_edit', {'id': project.id}) }}">edit</button >
                                                                    </td>
                                                                </tr>
                                                            {% else %}
                                                                <tr>
                                                                    <td colspan="12">no records found</td>
                                                                </tr>
                                                            {% endfor %}
                                                            </tbody>
                                                        <tfoot>
                                                            <tr>
                                                                <th>Id</th>
                                                                <th>Label</th>
                                                                <th>Creation_date</th>
                                                                <th>Manager</th>
                                                                <th>Status</th>
                                                                <th>actions</th>
                                                            </tr>
                                                        </tfoot>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                 <button class="btn btn-primary btn-square"> <a href="{{ path('app_project_new') }}">Create new</a></button >
                                </div>
                            </div>
                            <div id="styleSelector">
                            </div>
                        </div>
                    </div>
    
{% endblock %}

templates/project/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}
{% block head %}
<link rel="icon" href=" assets/images/favicon.ico" type="image/x-icon">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,800" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href=" bower_components/bootstrap/dist/css/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href=" assets/icon/themify-icons/themify-icons.css">

    <link rel="stylesheet" type="text/css" href=" assets/icon/icofont/css/icofont.css">

    <link rel="stylesheet" type="text/css" href=" assets/icon/feather/css/feather.css">

    <link rel="stylesheet" type="text/css" href=" assets/pages/j-pro/css/demo.css">
    <link rel="stylesheet" type="text/css" href=" assets/pages/j-pro/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href=" assets/pages/j-pro/css/j-pro-modern.css">

    <link rel="stylesheet" type="text/css" href=" assets/css/style.css">
    <link rel="stylesheet" type="text/css" href=" assets/css/jquery.mCustomScrollbar.css">
{% endblock %}
{% block body %}
     <div class="pcoded-content">
                        <div class="pcoded-inner-content">

                            <div class="main-body">
                                <div class="page-wrapper">

                                    <div class="page-header">
                                        <div class="row align-items-end">
                                            <div class="col-lg-8">
                                                <div class="page-header-title">
                                                    <div class="d-inline">
                                                        <h4>Add New Project</h4>
                                                        
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-lg-4">
                                                <div class="page-header-breadcrumb">
                                                    <ul class="breadcrumb-title">
                                                        <li class="breadcrumb-item" style="float: left;">
                                                            <a href="../index.html"> <i class="feather icon-home"></i>
                                                            </a>
                                                        </li>
                                                        <li class="breadcrumb-item" style="float: left;"><a
                                                                href="#!">Project list</a>
                                                        </li>
                                                        <li class="breadcrumb-item" style="float: left;"><a
                                                                href="#!">Add Project</a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>


                                    <div class="page-body">
                                        <div class="row">
                                            <div class="col-sm-12">

                                                <div class="card">
                                                    <div class="card-header">
                                                        <h5>New Project</h5>
                                                        
                                                           
                                                    </div>
                                                    <div class="card-block">
                                                        <div class="j-wrapper j-wrapper-640">
                                                        
                                                        {{ form_start(form,{'attr': {'class': 'j-pro','id':'j-pro'}})  }}
                                                            
                                                                
                                                                <div class="j-content">

                                                                    <div>
                                                                        <label class="j-label">Label</label>
                                                                        <div class="j-unit">
                                                                            <div class="j-input">
                                                                                <label class="j-icon-right" for="lable">
                                                                                   
                                                                                </label>
                                                                                
                                                                                    {{ form_widget(form.label,{'attr': {'id':'lable'}}) }}
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                    <div>
                                                                        <label class="j-label">Statut</label>
                                                                        <div class="j-unit">
                                                                            <div class="j-input">
                                                                                <label class="j-icon-right" for="statut">
                                                                                 
                                                                                </label>
                                                                                {{ form_widget(form.status,{'attr': {'id':'last_name'}}) }}
                                                                            </div>
                                                                        </div>
                                                                    </div>


                                                                    <div>
                                                                        <div>
                                                                            <label class="j-label">Manager</label>
                                                                        </div>
                                                                        <div class="j-unit">
                                                                            <div class="j-input">
                                                                                <label class="j-icon-right" for="manager">
                                                                                  
                                                                                </label>
                                                                                {{ form_widget(form.Manager,{'attr': {'id':'manger'}}) }}
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                  


                                                                    


                                                                   


                                                                   


                                                                    <div class="j-response"></div>

                                                                </div>
                                                                 <div class="form-check">

     


                                                                <div class="j-footer">
                                                                    <button type="submit"
                                                                        class="btn btn-primary" >{{ button_label|default('Save') }}</button>
                                                                </div>

                                                            
                                                           {{ form_end(form) }}
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>

                            <div id="styleSelector">
                            </div>
                        </div>
                    </div>
                    
{% endblock %}

templates/project/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Project{% endblock %}

{% block body %}
    <h1>Project</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ project.id }}</td>
            </tr>
            <tr>
                <th>Label</th>
                <td>{{ project.label }}</td>
            </tr>
            <tr>
                <th>Creation_date</th>
                <td>{{ project.creationDate ? project.creationDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ project.status }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_project_index') }}">back to list</a>

    <a href="{{ path('app_project_edit', {'id': project.id}) }}">edit</a>

    {{ include('project/_delete_form.html.twig') }}
{% endblock %}